#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: 192.168.136.160
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
dubbo:    #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
tanhua:
  sms:
    signName: 物流云商
    templateCode: SMS_106590012
    accessKey: LTAI4GKgob9vZ53k2SZdyAC7
    secret: LHLBvXmILRoyw0niRSBuXBZewQ30la
  email:
    user: 776239423@qq.com
    password: ysdimzjzxfqmbdeg
  oss:
    endpoint: oss-cn-qingdao.aliyuncs.com
    accessKeyId: LTAI5t8eyt6zxHZuE4QTcodc
    accessKeySecret: 8L3khm40RRbhZGn08s3ua3Wr8rMhjf
    bucket: tanhuaossservice
    url: https://tanhuaossservice.oss-cn-qingdao.aliyuncs.com/
  face:
    appId: 29202058
    apiKey: ptSnMDAm5LB1AsbiMidBZ4we
    secretKey: lAaU81AxY9BxP1ql4XdSGe2MF8ND0YK5